# Generated by Django 3.2.22 on 2023-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='genderValue',
        ),
    ]
